definitions:
  err.Error:
    properties:
      error:
        type: string
    type: object
  err.Errors:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  healthcheck.HealthcheckData:
    properties:
      message:
        type: string
      request_id:
        type: string
      status_code:
        type: integer
    type: object
  sentiment.Feed:
    description: Estrutura do feed de mensagens, associados a um usuário
    properties:
      messages:
        description: A lista de mensagens para aquele feed
        items:
          $ref: '#/definitions/sentiment.FeedMessage'
        type: array
      time_window_minutes:
        description: A janela de tempo, em minutos, na qual serão consideradas mensagens
          para a análise de sentimentos
        minimum: 0
        type: integer
    required:
    - messages
    type: object
  sentiment.FeedMessage:
    description: Estrutura de uma típica mensagem, associada a um feed de usuário
    properties:
      content:
        description: O conteúdo textual da mensagem
        maxLength: 280
        type: string
      hashtags:
        description: Lista de hashtags associadas às mensagens do feed
        items:
          type: string
        type: array
      id:
        description: O ID da mensagem, e.g. msg_123
        type: string
      parsedTimeStamp:
        type: string
      reactions:
        description: Total de reações a mensagem
        minimum: 0
        type: integer
      sentiment:
        $ref: '#/definitions/sentiment.MessageSentiment'
      shares:
        description: Total de cxompartilhamentos da mensagem
        minimum: 0
        type: integer
      timestamp:
        description: Data/hora local, em formato UTC (GMT - ZULU Time)
        type: string
      user_id:
        description: ID do usuário ao qual a mensagem está associada, e.g. user_324
        type: string
      views:
        description: Total de visualizações da mensagem
        minimum: 0
        type: integer
    required:
    - content
    - hashtags
    - id
    - timestamp
    - user_id
    type: object
  sentiment.FeedSentiment:
    properties:
      anomaly_detected:
        description: Indica se alguma anomalia no feed foi detectada
        type: boolean
      anomaly_type:
        description: Categoria da anomalia ("synchronized_posting" | "burst")
        type: string
      engagement_score:
        description: Índice de engajamento
        type: number
      flags:
        $ref: '#/definitions/sentiment.FeedSentimentFlags'
      influence_ranking:
        items:
          $ref: '#/definitions/sentiment.UserInfluenceRanking'
        type: array
      processing_time_ms:
        description: Auxiliar. Tempo de processamento da análise, em milissegundos
        type: number
      sentiment_distribution:
        $ref: '#/definitions/sentiment.FeedSentimentDistribution'
      trending_topics:
        description: Lista unificada de hashtags, citadas nas mensagens
        items:
          type: string
        type: array
    type: object
  sentiment.FeedSentimentDistribution:
    description: Percentuais dos sentimentos detectados das mensagens, por categoria
    properties:
      negative:
        description: Fração de mensagens com sentimento negativo
        type: number
      neutral:
        description: Fração de mensagens com sentimento nêutro
        type: number
      positive:
        description: Fração de mensagens com sentimento positivo
        type: number
    type: object
  sentiment.FeedSentimentFlags:
    description: Indicadores de casos especiais detectados nas mensagens
    properties:
      candidate_awareness:
        description: Indica se o conteúdo normalizado da mensagem corresponde a "teste
          tecnico mbras"
        type: boolean
      mbras_employee:
        description: Indica se o "user_id" contém a substring "mbras"
        type: boolean
      special_pattern:
        description: Indica a condição anterior e se também a mensagem possui exatamente
          42 caracteres
        type: boolean
    type: object
  sentiment.MessageSentiment:
    properties:
      label:
        description: Categoria do sentimento ("positive" | "negative" | "neutral"),
          de acordo com o valor do escore
        type: string
      processing_time_ms:
        description: Auxiliar. Tempo de processamento da análise em milissegundos
        type: number
      score:
        description: Número real, expressando quantitativamente o sentimento da mensagem
        type: number
    type: object
  sentiment.UserInfluenceRanking:
    description: Objeto contendo o índice de influência no feed para um usuário
    properties:
      influence_score:
        description: Índice de influência
        type: number
      user_id:
        description: Identificação do usuario, e.g. user_123
        type: string
    type: object
info:
  contact:
    name: Guilherme Gonçalves
    url: https://github.com/lwglg
  description: RESTful API providing sentimnet analysis for feeds' messages
  license:
    name: MIT License
    url: https://github.com/lwglg/gefuehlmesser/blob/main/LICENSE
  title: Gefuehlmesser API
  version: 1.0.0
paths:
  /api/v1/sentiment/feed:
    post:
      consumes:
      - application/json
      description: Realiza a análise determinística de sentimento das mensagens de
        um feed, dada uma payload de feed válida.
      parameters:
      - description: Payload contendo as mensagens de feed e parâmetro de janela temporal.
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sentiment.Feed'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sentiment.FeedSentiment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Análise de sentimento de feed
      tags:
      - API de análise de sentimentos
  /api/v1/sentiment/message:
    post:
      consumes:
      - application/json
      description: Realiza a análise determinística de sentimento de uma mensagem
        de feed, dada uma payload de feed válida.
      parameters:
      - description: Payload contendo a estrutura de uma mensagen de feed.
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/sentiment.FeedMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sentiment.MessageSentiment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Análise de sentimento de mensagem
      tags:
      - API de análise de sentimentos
  /utilitary/healthcheck:
    get:
      description: Realiza uma requisição de healthcheck ao servidor, retornnando
        uma mensagem simples.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.HealthcheckData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Healthcheck
      tags:
      - API utilitária
swagger: "2.0"
