name: Static Analysis

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "feature/*"
      - "bugfix/*"
      - "docs/*"
      - "refactor/*"
      - "develop"
      - "main"
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "docs/*"
      - "refactor/*"
      - "develop"
      - "main"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webservice
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: go mod package cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run unit tests
        run: go test ./...

      - name: Apply formatting on Go code
        run: ./bin/gofumpt -l -w . 2>&1 | tee outfile && test -z "$(cat outfile)" && rm outfile

      - name: Check for suspicious constructs in Go
        run: go vet ./...

      - name: Perform vulnerability check
        run: ./bin/govulncheck ./...
